### ISSUE TITLE
ignoring vendor assets

### ISSUE THREAD

**Issue by Olli** [Web-Ex-Machina/contao-locations#2]
Hi,
why is the vendor/assets path ignored by git?

**Comment by webexmachina** [comment]
Hi !
It was because we were in a rush and thought there was a better way to use external libraries than just including them in our git.
Didn't have the time to have it done it yet but we will !
If you have any suggestions, they are welcome :)

**Comment by Olli** [comment]
Why not include it? I have no clue why it shouln't be included. But I'm not very experienced.

**Comment by webexmachina** [comment]
When you use a library you don't own, you shouldn't include it in your repo. It should be included in your Composer. This way, you can manage the updates & releases to use in a better way than juste update your files.
But this is our way to manage this. It's not the only one.

**Comment by Olli** [comment]
Ok I tryed it but i don't know how to use an external package like mrohnstock/leaflet and put that javascripts into the assets for loading on the website.

**Comment by webexmachina** [comment]
Actually, you're right. There is no way I know to include external JS libraries correctly.
So here we are : the last release includes JVector & Leaflet directly in the repo. Thanks for your job !

**Comment by Olli** [comment]
Oh I just thought I'm just too stupid. ;)
